name: 'Check Changelog'
description: 'Check if the Changelog has been correctly modified'
inputs:
  github-token:
    description: 'Github Token'
    default: ${{ github.token }}
  repo:
    description: 'Repository name'
    default: ${{ github.repository }}
runs:
  using: 'node12'
  main: './dist/index.js'
