name: 'Check Changelog'
description: 'Check if the Changelog has been correctly modified'
inputs:
  github-token:
    description: 'Github Token'
    required: true
  repo:
    description: 'Repository name'
    required: true
  github-base-ref:
    description: 'Github Base Ref'
    required: true
  github-head-ref:
    description: 'Github Head Ref'
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
