name: 'Check Changelog'
description: 'Check if the Changelog has been correctly modified'
inputs:
  github-token:
    description: 'Github Token'
    required: true
  repo:
    description: 'Repository name'
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
